In [2]:
# ============================
# Importation des bibliothèques
# ============================

import GEOparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Affichage des graphiques dans Jupyter
%matplotlib inline

print("Toutes les bibliothèques sont importées avec succès !")

Toutes les bibliothèques sont importées avec succès !

In [3]:
print("Pandas :", pd.__version__)
print("Numpy :", np.__version__)
print("GEOparse :", GEOparse.__version__)

Pandas : 3.0.3
Numpy : 2.4.1
GEOparse : 2.0.4

In [4]:
# Télécharger le jeu de données GEO

import GEOparse

gse = GEOparse.get_GEO(
    geo="GSE104178",
    destdir="../data"
)

print("Téléchargement terminé !")

04-Aug-2026 19:44:25 DEBUG utils - Directory ../data already exists. Skipping.
04-Aug-2026 19:44:25 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE104nnn/GSE104178/soft/GSE104178_family.soft.gz to ../data\GSE104178_family.soft.gz
100%|██████████| 2.69k/2.69k [00:01<00:00, 1.93kB/s]
04-Aug-2026 19:44:29 DEBUG downloader - Size validation passed
04-Aug-2026 19:44:29 DEBUG downloader - Moving C:\Users\Dell\AppData\Local\Temp\tmpji44hqc0 to C:\Users\Dell\Documents\Stage bioinfo\data\GSE104178_family.soft.gz
04-Aug-2026 19:44:29 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE104nnn/GSE104178/soft/GSE104178_family.soft.gz
04-Aug-2026 19:44:29 INFO GEOparse - Parsing ../data\GSE104178_family.soft.gz:
04-Aug-2026 19:44:29 DEBUG GEOparse - DATABASE: GeoMiame
04-Aug-2026 19:44:29 DEBUG GEOparse - SERIES: GSE104178
04-Aug-2026 19:44:29 DEBUG GEOparse - PLATFORM: GPL11154
04-Aug-2026 19:44:29 DEBUG GEOparse - SAMPLE: GSM2791405
04-Aug-2026 19:44:29 DEBUG GEOparse - SAMPLE: GSM2791406
04-Aug-2026 19:44:29 DEBUG GEOparse - SAMPLE: GSM2791407
04-Aug-2026 19:44:29 DEBUG GEOparse - SAMPLE: GSM2791408
04-Aug-2026 19:44:29 DEBUG GEOparse - SAMPLE: GSM2791409
04-Aug-2026 19:44:29 DEBUG GEOparse - SAMPLE: GSM2791410

Téléchargement terminé !

In [5]:
print(type(gse))

<class 'GEOparse.GEOTypes.GSE'>

In [6]:
print(gse.name)

GSE104178

In [7]:
print(len(gse.gsms))

6

In [8]:
print(gse.metadata["title"])

['RNA-Sequencing approach for the identification of novel long non-coding RNA biomarkers in colorectal cancer']

In [9]:
print(gse.metadata["summary"])

['Long non-coding RNA (lncRNA) have been implicated in human pathology, however, their roles in colorectal carcinogenesis has not been fully elucidated. In the current study, whole-transcriptome was analyzed in 3 pairs of colorectal cancer (CRC) and matched normal mucosa (NM) by RNA sequencing (RNA-seq). Followed by confirmation using the Cancer Genome Atlas (TCGA) dataset, we identified 27 up-regulated and 22 down-regulated lncRNAs in CRC. Up-regulation of four lncRNAs, hereby named colorectal cancer associated lncRNA (CRCAL)-1 [AC021218.2], CRCAL-2 [LINC00858], CRCAL-3 [RP11-138J23.1] and CRCAL-4 [RP11-435O5.2], was further validated by real-time RT-PCR in 139 colorectal neoplasms and matched NM tissues. Knockdown of CRCAL-3 and CRCAL-4 in colon cancer cells reduced cell viability and colony formation ability, and induced cell cycle arrest. TCGA dataset supported the associations of CRCAL-3 and CRCAL-4 with cell cycle and revealed a co-expression network comprising dysregulated lncRNAs associated with protein-coding genes. In conclusion, RNA-seq identified numbers of novel lncRNAs dysregulated in CRC. In vitro experiments and GO term enrichment analysis indicated the functional relevance of CRCAL-3 and CRCAL-4 in association with cell cycle. Our data highlight the capability of RNA-seq to discover novel lncRNAs involved in human carcinogenesis, which may serve as alternative biomarkers and/or molecular treatment targets.']

In [10]:
print(type(gse))
print(gse.name)
print(len(gse.gsms))

<class 'GEOparse.GEOTypes.GSE'>
GSE104178
6

In [11]:
print(gse.metadata["title"])

['RNA-Sequencing approach for the identification of novel long non-coding RNA biomarkers in colorectal cancer']

In [12]:
# Nombre d'échantillons
print("Nombre d'échantillons :", len(gse.gsms))

# Liste des identifiants GSM
print("\nListe des GSM :")
for gsm in gse.gsms.keys():
    print(gsm)

Nombre d'échantillons : 6

Liste des GSM :
GSM2791405
GSM2791406
GSM2791407
GSM2791408
GSM2791409
GSM2791410

In [13]:
# Premier échantillon
gsm = list(gse.gsms.values())[0]

print("Nom :", gsm.name)
print("\nMétadonnées :\n")

for key, value in gsm.metadata.items():
    print(f"{key} : {value}")

Nom : GSM2791405

Métadonnées :

title : ['CXIR56SE6-CRC: colorectal cancer']
geo_accession : ['GSM2791405']
status : ['Public on Feb 14 2018']
submission_date : ['Sep 25 2017']
last_update_date : ['Mar 16 2023']
type : ['SRA']
channel_count : ['1']
source_name_ch1 : ['frozen mucosal tissue']
organism_ch1 : ['Homo sapiens']
taxid_ch1 : ['9606']
characteristics_ch1 : ['tissue: frozen mucosal tissue', 'tissue type: CRC: colorectal cancer', 'source id: CXIR56SE6']
molecule_ch1 : ['total RNA']
extract_protocol_ch1 : ['RNA was extracted using miRNeasy Mini Kit (QIAGEN, Hilden, Germany) according to the manufacturerâ€™s instruction. Briefly, 700 Î¼L of QIAzol was added to samples and homogenized with a TissueLyser LT (QIAGEN) for RNAlater immersed tissues or by vortexing for 1 minute for cultured cells. After incubation of the homogenate for 5 minutes at room temperature, 140 Î¼L chloroform was added and centrifuged at 12,000g and at 4Â°C for 15 minutes. Thereafter, transfer the upper aqueous phase to a new tube, and total RNA was extracted and eluted in 60 Î¼L of RNase-free water using QIAcube (QIAGEN).', 'Illumina TruSeq V2 kit']
data_processing : ['Novoalign+ V2.08.01 was used for alignment', 'Read count for each annotated transcript was then derived from mapped reads by Rsubread', 'Differential expression was determined by DESeq/edgeR', 'Genome_build: hg19', 'Supplementary_files_format_and_content: csv file; lncRNAs dysregulated in CRC as determined by edgeR (logFC and p val < 0.02) and DESeq (p val < 0.05)']
platform_id : ['GPL11154']
contact_name : ['Nicole,,Baldwin']
contact_email : ['Nicole.Baldwin@BSWHealth.org']
contact_institute : ['Baylor Research Institute']
contact_address : ['3434 Live Oak St']
contact_city : ['Dallas']
contact_zip/postal_code : ['75204']
contact_country : ['USA']
instrument_model : ['Illumina HiSeq 2000']
library_selection : ['cDNA']
library_source : ['transcriptomic']
library_strategy : ['RNA-Seq']
relation : ['BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN07692599', 'SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX3209932']
supplementary_file_1 : ['NONE']
series_id : ['GSE104178']
data_row_count : ['0']

In [14]:
gsm.table.head()

Empty DataFrame
Columns: []
Index: []

In [15]:
# Nombre d'échantillons
print("Nombre d'échantillons :", len(gse.gsms))

# Liste des identifiants GSM
print("\nListe des GSM :")
for gsm in gse.gsms.keys():
    print(gsm)

Nombre d'échantillons : 6

Liste des GSM :
GSM2791405
GSM2791406
GSM2791407
GSM2791408
GSM2791409
GSM2791410

In [16]:
# Premier échantillon
gsm = list(gse.gsms.values())[0]

print("Nom :", gsm.name)
print("\nMétadonnées :\n")

for key, value in gsm.metadata.items():
    print(f"{key} : {value}")

Nom : GSM2791405

Métadonnées :

title : ['CXIR56SE6-CRC: colorectal cancer']
geo_accession : ['GSM2791405']
status : ['Public on Feb 14 2018']
submission_date : ['Sep 25 2017']
last_update_date : ['Mar 16 2023']
type : ['SRA']
channel_count : ['1']
source_name_ch1 : ['frozen mucosal tissue']
organism_ch1 : ['Homo sapiens']
taxid_ch1 : ['9606']
characteristics_ch1 : ['tissue: frozen mucosal tissue', 'tissue type: CRC: colorectal cancer', 'source id: CXIR56SE6']
molecule_ch1 : ['total RNA']
extract_protocol_ch1 : ['RNA was extracted using miRNeasy Mini Kit (QIAGEN, Hilden, Germany) according to the manufacturerâ€™s instruction. Briefly, 700 Î¼L of QIAzol was added to samples and homogenized with a TissueLyser LT (QIAGEN) for RNAlater immersed tissues or by vortexing for 1 minute for cultured cells. After incubation of the homogenate for 5 minutes at room temperature, 140 Î¼L chloroform was added and centrifuged at 12,000g and at 4Â°C for 15 minutes. Thereafter, transfer the upper aqueous phase to a new tube, and total RNA was extracted and eluted in 60 Î¼L of RNase-free water using QIAcube (QIAGEN).', 'Illumina TruSeq V2 kit']
data_processing : ['Novoalign+ V2.08.01 was used for alignment', 'Read count for each annotated transcript was then derived from mapped reads by Rsubread', 'Differential expression was determined by DESeq/edgeR', 'Genome_build: hg19', 'Supplementary_files_format_and_content: csv file; lncRNAs dysregulated in CRC as determined by edgeR (logFC and p val < 0.02) and DESeq (p val < 0.05)']
platform_id : ['GPL11154']
contact_name : ['Nicole,,Baldwin']
contact_email : ['Nicole.Baldwin@BSWHealth.org']
contact_institute : ['Baylor Research Institute']
contact_address : ['3434 Live Oak St']
contact_city : ['Dallas']
contact_zip/postal_code : ['75204']
contact_country : ['USA']
instrument_model : ['Illumina HiSeq 2000']
library_selection : ['cDNA']
library_source : ['transcriptomic']
library_strategy : ['RNA-Seq']
relation : ['BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN07692599', 'SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX3209932']
supplementary_file_1 : ['NONE']
series_id : ['GSE104178']
data_row_count : ['0']

In [17]:
gsm.table.head()

Empty DataFrame
Columns: []
Index: []

In [18]:
# Afficher le type de tissu de chaque échantillon

for gsm_id, gsm in gse.gsms.items():
    print("=" * 60)
    print("Échantillon :", gsm_id)

    if "characteristics_ch1" in gsm.metadata:
        for info in gsm.metadata["characteristics_ch1"]:
            print(info)

============================================================
Échantillon : GSM2791405
tissue: frozen mucosal tissue
tissue type: CRC: colorectal cancer
source id: CXIR56SE6
============================================================
Échantillon : GSM2791406
tissue: frozen mucosal tissue
tissue type: CRC: colorectal cancer
source id: CXIR60OC4
============================================================
Échantillon : GSM2791407
tissue: frozen mucosal tissue
tissue type: CRC: colorectal cancer
source id: CXIR66OC21
============================================================
Échantillon : GSM2791408
tissue: frozen mucosal tissue
tissue type: matched normal mucosa (NM)
source id: CXIR56SE6
============================================================
Échantillon : GSM2791409
tissue: frozen mucosal tissue
tissue type: matched normal mucosa (NM)
source id: CXIR60OC4
============================================================
Échantillon : GSM2791410
tissue: frozen mucosal tissue
tissue type: matched normal mucosa (NM)
source id: CXIR66OC21

In [19]:
gsm = list(gse.gsms.values())[0]

print(gsm.table.head())
print("\nNombre de lignes :", len(gsm.table))

Empty DataFrame
Columns: []
Index: []

Nombre de lignes : 0